### ISSUE TITLE
You should use #game divs not body css 

### ISSUE THREAD

**Issue by jamieduk** [WebDevSimplified/JavaScript-Text-Adventure#1]
You should use #game divs not body css as people like me use header files and your css code messes that all up so instead use #game divs to then target your game code

also always put js files inside js folders same goes for css files inside css folders.

always use cursor:pointer for all buttons.

And you mispellt yours (in last scene).

Hope this feedback helps!

**Comment by WebDevSimplified** [comment]
Thanks for the feedback. The purpose of these videos is more for education than for direct copy paste of code. But I will keep this in mind for future videos.
